# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a51f1144fc205866e33d5dfbac2d354c2cbcebf3111a513220a1287f626ad6ea362da2629533bf5ef467963010fc82e29158a95fa11341cb299b58b18fd9f41

test:
  secret_key_base: 2363b618ba8ecb49dbc0efe9a6074687c45f1d47590abcfb3e5ae70ca47362d7b91d5155c2a8c5792b7b77c72a2e5e07bcb41c5544ca2282a861e03e51f37624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
